version: 2
updates:
- package-ecosystem: npm
  directory: "/webassemblyjs-repro"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  assignees:
  - xtuc
  versioning-strategy: widen
